stages:
  - pyflakes
  - build
  - pep8
  - deploy

variables:
  DEPENDENCIES: python3 gobject-introspection-devel gtk3-devel libmediaart-devel grilo-devel

pyflakes:
  stage: pyflakes
  script:
    - dnf install -y python3-pep8
    - python3-pyflakes .

build:
  stage: build
  script:
    - dnf install -y $DEPENDENCIES
    - git submodule update --init
    - ./autogen.sh
    - make

deploy:
  stage: deploy
  script:
    - dnf install -y $DEPENDENCIES
    - git submodule update --init
    - ./autogen.sh
    - make distcheck
  only:
    - tags

pep8:
  stage: pep8
  script:
    - dnf install -y python3-pep8
    - python3-pep8 --ignore=E501,E225,E265,E402 --show-source --show-pep8 .
  allow_failure: true