language: python
python:
  - "2.6"
  - "2.7"
  - "3.3"
install:
  - pip install pep8 pyflakes --use-mirrors
before_script:
  - "pep8 --ignore=E501,E225 gnome-music"
script:
  - "pyflakes gnome-music"
