language: python
python:
  - "3.3"
install:
  - pip install pep8 pyflakes --use-mirrors
script:
  - "pyflakes gnomemusic"
  - "pep8 --ignore=E501,E225,E265,E402 --show-source --show-pep8 gnomemusic"
after_success:
  - if [ -z "$TRAVIS_TAG" ]; then
      echo "Making a package"
    else
      echo "NOPE!"
    fi
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/288e384c48dc6f7d1de0
    on_success: change
    on_failure: always
    on_start: false
