language: python
python:
  - "3.3"
before_install:
  - echo "deb http://archive.ubuntu.com/ubuntu/ utopic main restricted universe multiverse" | sudo tee -a /etc/apt/sources.list
  - sudo apt-get update -qq
  - sudo apt-get install -qq gnome-common gnome-doc-utils libgrilo-0.2-dev gnome-pkg-tools gobject-introspection libgirepository1.0-dev libglib2.0-dev libgtk-3-dev libexpat1-dev libmediaart-1.0-dev yelp-tools
install:
  - pip install pep8 pyflakes --use-mirrors
script:
  - "pyflakes gnomemusic"
  - "pep8 --ignore=E501,E225,E265,E402 --show-source --show-pep8 gnomemusic"
  - "./autogen.sh"
  - "make"
  - "make distcheck"
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/288e384c48dc6f7d1de0
    on_success: change
    on_failure: always
    on_start: false
