sudo: required
services: docker
language: python
python:
  - "3.3"
env:
 - TESTS="pyflakes"
 - TESTS="pep8"
 - TESTS="build"
 - TESTS="tarball"

matrix:
  allow_failures:
    - env: TESTS="pep8"
    - env: TESTS="pyflakes"

before_install:
  - docker pull fedora
  - pip install pep8 pyflakes --use-mirrors

script:
- case $TESTS in
  pep8) pep8 --ignore=E501,E225,E265,E402 --show-source --show-pep8 gnomemusic ;;
  pyflakes) pyflakes gnomemusic ;;
  build) docker run -P -v $(pwd):/app --rm fedora "/bin/sh" "/app/ci_build.sh" ;;
  tarball) echo "$$TRAVIS_TAG" ;;
  esac
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/288e384c48dc6f7d1de0
    on_success: change
    on_failure: always
