sudo: required
services: docker
language: python
env:
 - TEST="pyflakes"
 - TEST="pep8"
 - TEST="build"

matrix:
  allow_failures:
    - env: TEST="pep8"

script:
- docker run -P -v $(pwd):/mnt --rm fedora:rawhide "/bin/sh" "/mnt/ci_$TEST.sh"
